language: python
python:
  - "2.7"
  - "3.4"

cache: pip

install:
    - pip install travis-sphinx sphinx
    - pip install -e . 

script:
    - python setup.py test
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis-sphinx --source=docs build; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis-sphinx deploy; fi
