language: python
python:
  - "2.7"

install:
    - pip install travis-sphinx sphinx
    - pip install -e . 

script:
    - python setup.py build
    - travis-sphinx --source=docs build

after_success:
    - travis-sphinx deploy
