language: python
python:
  - "2.7"
  - "3.4"

cache: pip

install:
    - pip install travis-sphinx sphinx
    - pip install -e . 

script:
    - python setup.py test
    - travis-sphinx --source=docs build

after_success:
    - travis-sphinx deploy
