# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.branches_info import BranchesInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestBranchesInfo(unittest.TestCase):
    """BranchesInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BranchesInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.branches_info.BranchesInfo()  # noqa: E501
        if include_optional :
            return BranchesInfo(
                main_branch_name = '0', 
                branch_names = [
                    '0'
                    ], 
                deleted_branches = [
                    '0'
                    ], 
                anonymous_branches = [
                    '0'
                    ], 
                aliases = {
                    'key' : '0'
                    }
            )
        else :
            return BranchesInfo(
        )

    def testBranchesInfo(self):
        """Test BranchesInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
