# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.architecture_api import ArchitectureApi  # noqa: E501
from openapi_client.rest import ApiException


class TestArchitectureApi(unittest.TestCase):
    """ArchitectureApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.architecture_api.ArchitectureApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_architecture_assessments(self):
        """Test case for get_all_architecture_assessments

        Get all architecture assessments  # noqa: E501
        """
        pass

    def test_upload_architecture(self):
        """Test case for upload_architecture

        Upload architecture  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
