# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calculate_project_mappings(self):
        """Test case for calculate_project_mappings

        Calculate project mappings  # noqa: E501
        """
        pass

    def test_get_dashboard_gadget(self):
        """Test case for get_dashboard_gadget

        Get the dashboard gadget  # noqa: E501
        """
        pass

    def test_get_dashboard_thumbnail(self):
        """Test case for get_dashboard_thumbnail

        Get the thumbnail of the Jira dashboard gadget  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
