# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.findings_summary_category_info import FindingsSummaryCategoryInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestFindingsSummaryCategoryInfo(unittest.TestCase):
    """FindingsSummaryCategoryInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FindingsSummaryCategoryInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.findings_summary_category_info.FindingsSummaryCategoryInfo()  # noqa: E501
        if include_optional :
            return FindingsSummaryCategoryInfo(
                category_name = '0', 
                count = 56, 
                count_red = 56, 
                group_infos = [
                    openapi_client.models.findings_summary_group_info.FindingsSummaryGroupInfo(
                        group_name = '0', 
                        count = 56, 
                        count_red = 56, 
                        type_id_infos = [
                            openapi_client.models.findings_summary_type_id_info.FindingsSummaryTypeIdInfo(
                                type_id_name = '0', 
                                count = 56, 
                                count_red = 56, )
                            ], )
                    ]
            )
        else :
            return FindingsSummaryCategoryInfo(
        )

    def testFindingsSummaryCategoryInfo(self):
        """Test FindingsSummaryCategoryInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
