# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.external_metrics_api import ExternalMetricsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestExternalMetricsApi(unittest.TestCase):
    """ExternalMetricsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.external_metrics_api.ExternalMetricsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_put_external_metrics(self):
        """Test case for put_external_metrics

        Add or update metrics  # noqa: E501
        """
        pass

    def test_upload_external_metrics(self):
        """Test case for upload_external_metrics

        Upload external metrics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
