# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.qualified_name_location_all_of import QualifiedNameLocationAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestQualifiedNameLocationAllOf(unittest.TestCase):
    """QualifiedNameLocationAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test QualifiedNameLocationAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.qualified_name_location_all_of.QualifiedNameLocationAllOf()  # noqa: E501
        if include_optional :
            return QualifiedNameLocationAllOf(
                qualified_name = '0', 
                abbreviated = True, 
                signal_names = [
                    '0'
                    ]
            )
        else :
            return QualifiedNameLocationAllOf(
        )

    def testQualifiedNameLocationAllOf(self):
        """Test QualifiedNameLocationAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
