# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.text_region_location_all_of import TextRegionLocationAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestTextRegionLocationAllOf(unittest.TestCase):
    """TextRegionLocationAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TextRegionLocationAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.text_region_location_all_of.TextRegionLocationAllOf()  # noqa: E501
        if include_optional :
            return TextRegionLocationAllOf(
                raw_start_offset = 56, 
                raw_end_offset = 56, 
                raw_start_line = 56, 
                raw_end_line = 56, 
                type = '0'
            )
        else :
            return TextRegionLocationAllOf(
        )

    def testTextRegionLocationAllOf(self):
        """Test TextRegionLocationAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
