# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.delta_api import DeltaApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDeltaApi(unittest.TestCase):
    """DeltaApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.delta_api.DeltaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_finding_delta_badge(self):
        """Test case for get_finding_delta_badge

        Get finding delta badge  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
