# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.tracked_finding_with_diff_info import TrackedFindingWithDiffInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestTrackedFindingWithDiffInfo(unittest.TestCase):
    """TrackedFindingWithDiffInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TrackedFindingWithDiffInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.tracked_finding_with_diff_info.TrackedFindingWithDiffInfo()  # noqa: E501
        if include_optional :
            return TrackedFindingWithDiffInfo(
                location = openapi_client.models.element_location.ElementLocation(
                    location = '0', 
                    uniform_path = '0', 
                    type = '0', ), 
                group_name = '0', 
                category_name = '0', 
                message = '0', 
                assessment = 'RED', 
                sibling_locations = [
                    openapi_client.models.element_location.ElementLocation(
                        location = '0', 
                        uniform_path = '0', 
                        type = '0', )
                    ], 
                secondary_locations = [
                    openapi_client.models.element_location.ElementLocation(
                        location = '0', 
                        uniform_path = '0', 
                        type = '0', )
                    ], 
                properties = {
                    'key' : None
                    }, 
                statement_path = [
                    openapi_client.models.statement_path_element.StatementPathElement(
                        predecessors = [
                            56
                            ], 
                        location = openapi_client.models.element_location.ElementLocation(
                            uniform_path = '0', 
                            type = '0', ), 
                        description = '0', )
                    ], 
                analysis_timestamp = 56, 
                type_id = '0', 
                id = '0', 
                birth = openapi_client.models.commit_descriptor.CommitDescriptor(
                    branch_name = '0', 
                    timestamp = 56, ), 
                death = openapi_client.models.commit_descriptor.CommitDescriptor(
                    branch_name = '0', 
                    timestamp = 56, ), 
                creation_diff = openapi_client.models.diff_input_description.DiffInputDescription(
                    left = openapi_client.models.diff_input_location.DiffInputLocation(
                        uniform_path = '0', 
                        commit = openapi_client.models.commit_descriptor.CommitDescriptor(
                            branch_name = '0', 
                            timestamp = 56, ), 
                        line_number = 56, ), 
                    right = openapi_client.models.diff_input_location.DiffInputLocation(
                        uniform_path = '0', 
                        line_number = 56, ), ), 
                created_by_other_change = True, 
                removal_diff = openapi_client.models.diff_input_description.DiffInputDescription(
                    left = openapi_client.models.diff_input_location.DiffInputLocation(
                        uniform_path = '0', 
                        commit = openapi_client.models.commit_descriptor.CommitDescriptor(
                            branch_name = '0', 
                            timestamp = 56, ), 
                        line_number = 56, ), 
                    right = openapi_client.models.diff_input_location.DiffInputLocation(
                        uniform_path = '0', 
                        line_number = 56, ), ), 
                removed_by_other_change = True
            )
        else :
            return TrackedFindingWithDiffInfo(
        )

    def testTrackedFindingWithDiffInfo(self):
        """Test TrackedFindingWithDiffInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
