# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class EvaluatedMetricThreshold(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'options': 'dict(str, str)',
        'custom_name': 'str',
        'threshold_yellow': 'float',
        'threshold_red': 'float',
        'sub_path': 'str',
        'metric_schema_source': 'str',
        'assessment_specification': 'str',
        'evaluation_options': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'options': 'options',
        'custom_name': 'customName',
        'threshold_yellow': 'thresholdYellow',
        'threshold_red': 'thresholdRed',
        'sub_path': 'subPath',
        'metric_schema_source': 'metricSchemaSource',
        'assessment_specification': 'assessmentSpecification',
        'evaluation_options': 'evaluationOptions'
    }

    def __init__(self, name=None, options=None, custom_name=None, threshold_yellow=None, threshold_red=None, sub_path=None, metric_schema_source=None, assessment_specification=None, evaluation_options=None, local_vars_configuration=None):  # noqa: E501
        """EvaluatedMetricThreshold - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._options = None
        self._custom_name = None
        self._threshold_yellow = None
        self._threshold_red = None
        self._sub_path = None
        self._metric_schema_source = None
        self._assessment_specification = None
        self._evaluation_options = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if options is not None:
            self.options = options
        if custom_name is not None:
            self.custom_name = custom_name
        if threshold_yellow is not None:
            self.threshold_yellow = threshold_yellow
        if threshold_red is not None:
            self.threshold_red = threshold_red
        if sub_path is not None:
            self.sub_path = sub_path
        if metric_schema_source is not None:
            self.metric_schema_source = metric_schema_source
        if assessment_specification is not None:
            self.assessment_specification = assessment_specification
        if evaluation_options is not None:
            self.evaluation_options = evaluation_options

    @property
    def name(self):
        """Gets the name of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The name of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EvaluatedMetricThreshold.


        :param name: The name of this EvaluatedMetricThreshold.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def options(self):
        """Gets the options of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The options of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this EvaluatedMetricThreshold.


        :param options: The options of this EvaluatedMetricThreshold.  # noqa: E501
        :type: dict(str, str)
        """

        self._options = options

    @property
    def custom_name(self):
        """Gets the custom_name of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The custom_name of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: str
        """
        return self._custom_name

    @custom_name.setter
    def custom_name(self, custom_name):
        """Sets the custom_name of this EvaluatedMetricThreshold.


        :param custom_name: The custom_name of this EvaluatedMetricThreshold.  # noqa: E501
        :type: str
        """

        self._custom_name = custom_name

    @property
    def threshold_yellow(self):
        """Gets the threshold_yellow of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The threshold_yellow of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: float
        """
        return self._threshold_yellow

    @threshold_yellow.setter
    def threshold_yellow(self, threshold_yellow):
        """Sets the threshold_yellow of this EvaluatedMetricThreshold.


        :param threshold_yellow: The threshold_yellow of this EvaluatedMetricThreshold.  # noqa: E501
        :type: float
        """

        self._threshold_yellow = threshold_yellow

    @property
    def threshold_red(self):
        """Gets the threshold_red of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The threshold_red of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: float
        """
        return self._threshold_red

    @threshold_red.setter
    def threshold_red(self, threshold_red):
        """Sets the threshold_red of this EvaluatedMetricThreshold.


        :param threshold_red: The threshold_red of this EvaluatedMetricThreshold.  # noqa: E501
        :type: float
        """

        self._threshold_red = threshold_red

    @property
    def sub_path(self):
        """Gets the sub_path of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The sub_path of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: str
        """
        return self._sub_path

    @sub_path.setter
    def sub_path(self, sub_path):
        """Sets the sub_path of this EvaluatedMetricThreshold.


        :param sub_path: The sub_path of this EvaluatedMetricThreshold.  # noqa: E501
        :type: str
        """

        self._sub_path = sub_path

    @property
    def metric_schema_source(self):
        """Gets the metric_schema_source of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The metric_schema_source of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: str
        """
        return self._metric_schema_source

    @metric_schema_source.setter
    def metric_schema_source(self, metric_schema_source):
        """Sets the metric_schema_source of this EvaluatedMetricThreshold.


        :param metric_schema_source: The metric_schema_source of this EvaluatedMetricThreshold.  # noqa: E501
        :type: str
        """
        allowed_values = ["CODE_METRICS", "NON_CODE_METRICS", "TEST_EXECUTION_METRICS", "ISSUE_METRICS"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and metric_schema_source not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `metric_schema_source` ({0}), must be one of {1}"  # noqa: E501
                .format(metric_schema_source, allowed_values)
            )

        self._metric_schema_source = metric_schema_source

    @property
    def assessment_specification(self):
        """Gets the assessment_specification of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The assessment_specification of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: str
        """
        return self._assessment_specification

    @assessment_specification.setter
    def assessment_specification(self, assessment_specification):
        """Sets the assessment_specification of this EvaluatedMetricThreshold.


        :param assessment_specification: The assessment_specification of this EvaluatedMetricThreshold.  # noqa: E501
        :type: str
        """
        allowed_values = ["DEFAULT", "FORCE_LOW_IS_BAD", "FORCE_HIGH_IS_BAD"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and assessment_specification not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `assessment_specification` ({0}), must be one of {1}"  # noqa: E501
                .format(assessment_specification, allowed_values)
            )

        self._assessment_specification = assessment_specification

    @property
    def evaluation_options(self):
        """Gets the evaluation_options of this EvaluatedMetricThreshold.  # noqa: E501


        :return: The evaluation_options of this EvaluatedMetricThreshold.  # noqa: E501
        :rtype: list[str]
        """
        return self._evaluation_options

    @evaluation_options.setter
    def evaluation_options(self, evaluation_options):
        """Sets the evaluation_options of this EvaluatedMetricThreshold.


        :param evaluation_options: The evaluation_options of this EvaluatedMetricThreshold.  # noqa: E501
        :type: list[str]
        """
        allowed_values = ["ASSESSMENT_METRIC_RED_IF_ANY_THRESHOLD_VIOLATED"]  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                not set(evaluation_options).issubset(set(allowed_values))):  # noqa: E501
            raise ValueError(
                "Invalid values for `evaluation_options` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(evaluation_options) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._evaluation_options = evaluation_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EvaluatedMetricThreshold):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EvaluatedMetricThreshold):
            return True

        return self.to_dict() != other.to_dict()
