# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class FindingDelta(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'added_findings': 'list[TrackedFinding]',
        'findings_in_changed_code': 'list[TrackedFinding]',
        'removed_findings': 'list[TrackedFinding]',
        'number_of_added_findings': 'int',
        'number_of_findings_in_changed_code': 'int',
        'number_of_removed_findings': 'int',
        'finding_summary': 'list[FindingsSummaryCategoryInfo]'
    }

    attribute_map = {
        'added_findings': 'addedFindings',
        'findings_in_changed_code': 'findingsInChangedCode',
        'removed_findings': 'removedFindings',
        'number_of_added_findings': 'numberOfAddedFindings',
        'number_of_findings_in_changed_code': 'numberOfFindingsInChangedCode',
        'number_of_removed_findings': 'numberOfRemovedFindings',
        'finding_summary': 'findingSummary'
    }

    def __init__(self, added_findings=None, findings_in_changed_code=None, removed_findings=None, number_of_added_findings=None, number_of_findings_in_changed_code=None, number_of_removed_findings=None, finding_summary=None, local_vars_configuration=None):  # noqa: E501
        """FindingDelta - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._added_findings = None
        self._findings_in_changed_code = None
        self._removed_findings = None
        self._number_of_added_findings = None
        self._number_of_findings_in_changed_code = None
        self._number_of_removed_findings = None
        self._finding_summary = None
        self.discriminator = None

        if added_findings is not None:
            self.added_findings = added_findings
        if findings_in_changed_code is not None:
            self.findings_in_changed_code = findings_in_changed_code
        if removed_findings is not None:
            self.removed_findings = removed_findings
        if number_of_added_findings is not None:
            self.number_of_added_findings = number_of_added_findings
        if number_of_findings_in_changed_code is not None:
            self.number_of_findings_in_changed_code = number_of_findings_in_changed_code
        if number_of_removed_findings is not None:
            self.number_of_removed_findings = number_of_removed_findings
        if finding_summary is not None:
            self.finding_summary = finding_summary

    @property
    def added_findings(self):
        """Gets the added_findings of this FindingDelta.  # noqa: E501


        :return: The added_findings of this FindingDelta.  # noqa: E501
        :rtype: list[TrackedFinding]
        """
        return self._added_findings

    @added_findings.setter
    def added_findings(self, added_findings):
        """Sets the added_findings of this FindingDelta.


        :param added_findings: The added_findings of this FindingDelta.  # noqa: E501
        :type: list[TrackedFinding]
        """

        self._added_findings = added_findings

    @property
    def findings_in_changed_code(self):
        """Gets the findings_in_changed_code of this FindingDelta.  # noqa: E501


        :return: The findings_in_changed_code of this FindingDelta.  # noqa: E501
        :rtype: list[TrackedFinding]
        """
        return self._findings_in_changed_code

    @findings_in_changed_code.setter
    def findings_in_changed_code(self, findings_in_changed_code):
        """Sets the findings_in_changed_code of this FindingDelta.


        :param findings_in_changed_code: The findings_in_changed_code of this FindingDelta.  # noqa: E501
        :type: list[TrackedFinding]
        """

        self._findings_in_changed_code = findings_in_changed_code

    @property
    def removed_findings(self):
        """Gets the removed_findings of this FindingDelta.  # noqa: E501


        :return: The removed_findings of this FindingDelta.  # noqa: E501
        :rtype: list[TrackedFinding]
        """
        return self._removed_findings

    @removed_findings.setter
    def removed_findings(self, removed_findings):
        """Sets the removed_findings of this FindingDelta.


        :param removed_findings: The removed_findings of this FindingDelta.  # noqa: E501
        :type: list[TrackedFinding]
        """

        self._removed_findings = removed_findings

    @property
    def number_of_added_findings(self):
        """Gets the number_of_added_findings of this FindingDelta.  # noqa: E501


        :return: The number_of_added_findings of this FindingDelta.  # noqa: E501
        :rtype: int
        """
        return self._number_of_added_findings

    @number_of_added_findings.setter
    def number_of_added_findings(self, number_of_added_findings):
        """Sets the number_of_added_findings of this FindingDelta.


        :param number_of_added_findings: The number_of_added_findings of this FindingDelta.  # noqa: E501
        :type: int
        """

        self._number_of_added_findings = number_of_added_findings

    @property
    def number_of_findings_in_changed_code(self):
        """Gets the number_of_findings_in_changed_code of this FindingDelta.  # noqa: E501


        :return: The number_of_findings_in_changed_code of this FindingDelta.  # noqa: E501
        :rtype: int
        """
        return self._number_of_findings_in_changed_code

    @number_of_findings_in_changed_code.setter
    def number_of_findings_in_changed_code(self, number_of_findings_in_changed_code):
        """Sets the number_of_findings_in_changed_code of this FindingDelta.


        :param number_of_findings_in_changed_code: The number_of_findings_in_changed_code of this FindingDelta.  # noqa: E501
        :type: int
        """

        self._number_of_findings_in_changed_code = number_of_findings_in_changed_code

    @property
    def number_of_removed_findings(self):
        """Gets the number_of_removed_findings of this FindingDelta.  # noqa: E501


        :return: The number_of_removed_findings of this FindingDelta.  # noqa: E501
        :rtype: int
        """
        return self._number_of_removed_findings

    @number_of_removed_findings.setter
    def number_of_removed_findings(self, number_of_removed_findings):
        """Sets the number_of_removed_findings of this FindingDelta.


        :param number_of_removed_findings: The number_of_removed_findings of this FindingDelta.  # noqa: E501
        :type: int
        """

        self._number_of_removed_findings = number_of_removed_findings

    @property
    def finding_summary(self):
        """Gets the finding_summary of this FindingDelta.  # noqa: E501


        :return: The finding_summary of this FindingDelta.  # noqa: E501
        :rtype: list[FindingsSummaryCategoryInfo]
        """
        return self._finding_summary

    @finding_summary.setter
    def finding_summary(self, finding_summary):
        """Sets the finding_summary of this FindingDelta.


        :param finding_summary: The finding_summary of this FindingDelta.  # noqa: E501
        :type: list[FindingsSummaryCategoryInfo]
        """

        self._finding_summary = finding_summary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FindingDelta):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FindingDelta):
            return True

        return self.to_dict() != other.to_dict()
