# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class FindingBlacklistRequestBody(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'blacklist_info': 'FindingBlacklistInfo',
        'finding_ids': 'list[str]'
    }

    attribute_map = {
        'blacklist_info': 'blacklistInfo',
        'finding_ids': 'findingIds'
    }

    def __init__(self, blacklist_info=None, finding_ids=None, local_vars_configuration=None):  # noqa: E501
        """FindingBlacklistRequestBody - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._blacklist_info = None
        self._finding_ids = None
        self.discriminator = None

        if blacklist_info is not None:
            self.blacklist_info = blacklist_info
        if finding_ids is not None:
            self.finding_ids = finding_ids

    @property
    def blacklist_info(self):
        """Gets the blacklist_info of this FindingBlacklistRequestBody.  # noqa: E501


        :return: The blacklist_info of this FindingBlacklistRequestBody.  # noqa: E501
        :rtype: FindingBlacklistInfo
        """
        return self._blacklist_info

    @blacklist_info.setter
    def blacklist_info(self, blacklist_info):
        """Sets the blacklist_info of this FindingBlacklistRequestBody.


        :param blacklist_info: The blacklist_info of this FindingBlacklistRequestBody.  # noqa: E501
        :type: FindingBlacklistInfo
        """

        self._blacklist_info = blacklist_info

    @property
    def finding_ids(self):
        """Gets the finding_ids of this FindingBlacklistRequestBody.  # noqa: E501


        :return: The finding_ids of this FindingBlacklistRequestBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._finding_ids

    @finding_ids.setter
    def finding_ids(self, finding_ids):
        """Sets the finding_ids of this FindingBlacklistRequestBody.


        :param finding_ids: The finding_ids of this FindingBlacklistRequestBody.  # noqa: E501
        :type: list[str]
        """

        self._finding_ids = finding_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FindingBlacklistRequestBody):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FindingBlacklistRequestBody):
            return True

        return self.to_dict() != other.to_dict()
