# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PreCommitServerLimits(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_count_limit': 'int',
        'file_size_limit_in_bytes': 'int',
        'time_limit_in_seconds': 'int'
    }

    attribute_map = {
        'file_count_limit': 'fileCountLimit',
        'file_size_limit_in_bytes': 'fileSizeLimitInBytes',
        'time_limit_in_seconds': 'timeLimitInSeconds'
    }

    def __init__(self, file_count_limit=None, file_size_limit_in_bytes=None, time_limit_in_seconds=None, local_vars_configuration=None):  # noqa: E501
        """PreCommitServerLimits - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file_count_limit = None
        self._file_size_limit_in_bytes = None
        self._time_limit_in_seconds = None
        self.discriminator = None

        if file_count_limit is not None:
            self.file_count_limit = file_count_limit
        if file_size_limit_in_bytes is not None:
            self.file_size_limit_in_bytes = file_size_limit_in_bytes
        if time_limit_in_seconds is not None:
            self.time_limit_in_seconds = time_limit_in_seconds

    @property
    def file_count_limit(self):
        """Gets the file_count_limit of this PreCommitServerLimits.  # noqa: E501


        :return: The file_count_limit of this PreCommitServerLimits.  # noqa: E501
        :rtype: int
        """
        return self._file_count_limit

    @file_count_limit.setter
    def file_count_limit(self, file_count_limit):
        """Sets the file_count_limit of this PreCommitServerLimits.


        :param file_count_limit: The file_count_limit of this PreCommitServerLimits.  # noqa: E501
        :type: int
        """

        self._file_count_limit = file_count_limit

    @property
    def file_size_limit_in_bytes(self):
        """Gets the file_size_limit_in_bytes of this PreCommitServerLimits.  # noqa: E501


        :return: The file_size_limit_in_bytes of this PreCommitServerLimits.  # noqa: E501
        :rtype: int
        """
        return self._file_size_limit_in_bytes

    @file_size_limit_in_bytes.setter
    def file_size_limit_in_bytes(self, file_size_limit_in_bytes):
        """Sets the file_size_limit_in_bytes of this PreCommitServerLimits.


        :param file_size_limit_in_bytes: The file_size_limit_in_bytes of this PreCommitServerLimits.  # noqa: E501
        :type: int
        """

        self._file_size_limit_in_bytes = file_size_limit_in_bytes

    @property
    def time_limit_in_seconds(self):
        """Gets the time_limit_in_seconds of this PreCommitServerLimits.  # noqa: E501


        :return: The time_limit_in_seconds of this PreCommitServerLimits.  # noqa: E501
        :rtype: int
        """
        return self._time_limit_in_seconds

    @time_limit_in_seconds.setter
    def time_limit_in_seconds(self, time_limit_in_seconds):
        """Sets the time_limit_in_seconds of this PreCommitServerLimits.


        :param time_limit_in_seconds: The time_limit_in_seconds of this PreCommitServerLimits.  # noqa: E501
        :type: int
        """

        self._time_limit_in_seconds = time_limit_in_seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PreCommitServerLimits):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PreCommitServerLimits):
            return True

        return self.to_dict() != other.to_dict()
