# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ProjectConfiguration(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'id': 'str',
        'profile': 'str',
        'alias': 'str',
        'parent_project_id': 'str',
        'description': 'str',
        'embedded_profile': 'AnalysisProfile',
        'metric_threshold_configuration': 'MetricThresholdConfiguration',
        'connectors': 'list[ConnectorConfiguration]'
    }

    attribute_map = {
        'name': 'name',
        'id': 'id',
        'profile': 'profile',
        'alias': 'alias',
        'parent_project_id': 'parentProjectId',
        'description': 'description',
        'embedded_profile': 'embeddedProfile',
        'metric_threshold_configuration': 'metricThresholdConfiguration',
        'connectors': 'connectors'
    }

    def __init__(self, name=None, id=None, profile=None, alias=None, parent_project_id=None, description=None, embedded_profile=None, metric_threshold_configuration=None, connectors=None, local_vars_configuration=None):  # noqa: E501
        """ProjectConfiguration - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._id = None
        self._profile = None
        self._alias = None
        self._parent_project_id = None
        self._description = None
        self._embedded_profile = None
        self._metric_threshold_configuration = None
        self._connectors = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if id is not None:
            self.id = id
        if profile is not None:
            self.profile = profile
        if alias is not None:
            self.alias = alias
        if parent_project_id is not None:
            self.parent_project_id = parent_project_id
        if description is not None:
            self.description = description
        if embedded_profile is not None:
            self.embedded_profile = embedded_profile
        if metric_threshold_configuration is not None:
            self.metric_threshold_configuration = metric_threshold_configuration
        if connectors is not None:
            self.connectors = connectors

    @property
    def name(self):
        """Gets the name of this ProjectConfiguration.  # noqa: E501


        :return: The name of this ProjectConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectConfiguration.


        :param name: The name of this ProjectConfiguration.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this ProjectConfiguration.  # noqa: E501


        :return: The id of this ProjectConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectConfiguration.


        :param id: The id of this ProjectConfiguration.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def profile(self):
        """Gets the profile of this ProjectConfiguration.  # noqa: E501


        :return: The profile of this ProjectConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this ProjectConfiguration.


        :param profile: The profile of this ProjectConfiguration.  # noqa: E501
        :type: str
        """

        self._profile = profile

    @property
    def alias(self):
        """Gets the alias of this ProjectConfiguration.  # noqa: E501


        :return: The alias of this ProjectConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this ProjectConfiguration.


        :param alias: The alias of this ProjectConfiguration.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def parent_project_id(self):
        """Gets the parent_project_id of this ProjectConfiguration.  # noqa: E501


        :return: The parent_project_id of this ProjectConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._parent_project_id

    @parent_project_id.setter
    def parent_project_id(self, parent_project_id):
        """Sets the parent_project_id of this ProjectConfiguration.


        :param parent_project_id: The parent_project_id of this ProjectConfiguration.  # noqa: E501
        :type: str
        """

        self._parent_project_id = parent_project_id

    @property
    def description(self):
        """Gets the description of this ProjectConfiguration.  # noqa: E501


        :return: The description of this ProjectConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProjectConfiguration.


        :param description: The description of this ProjectConfiguration.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def embedded_profile(self):
        """Gets the embedded_profile of this ProjectConfiguration.  # noqa: E501


        :return: The embedded_profile of this ProjectConfiguration.  # noqa: E501
        :rtype: AnalysisProfile
        """
        return self._embedded_profile

    @embedded_profile.setter
    def embedded_profile(self, embedded_profile):
        """Sets the embedded_profile of this ProjectConfiguration.


        :param embedded_profile: The embedded_profile of this ProjectConfiguration.  # noqa: E501
        :type: AnalysisProfile
        """

        self._embedded_profile = embedded_profile

    @property
    def metric_threshold_configuration(self):
        """Gets the metric_threshold_configuration of this ProjectConfiguration.  # noqa: E501


        :return: The metric_threshold_configuration of this ProjectConfiguration.  # noqa: E501
        :rtype: MetricThresholdConfiguration
        """
        return self._metric_threshold_configuration

    @metric_threshold_configuration.setter
    def metric_threshold_configuration(self, metric_threshold_configuration):
        """Sets the metric_threshold_configuration of this ProjectConfiguration.


        :param metric_threshold_configuration: The metric_threshold_configuration of this ProjectConfiguration.  # noqa: E501
        :type: MetricThresholdConfiguration
        """

        self._metric_threshold_configuration = metric_threshold_configuration

    @property
    def connectors(self):
        """Gets the connectors of this ProjectConfiguration.  # noqa: E501


        :return: The connectors of this ProjectConfiguration.  # noqa: E501
        :rtype: list[ConnectorConfiguration]
        """
        return self._connectors

    @connectors.setter
    def connectors(self, connectors):
        """Sets the connectors of this ProjectConfiguration.


        :param connectors: The connectors of this ProjectConfiguration.  # noqa: E501
        :type: list[ConnectorConfiguration]
        """

        self._connectors = connectors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectConfiguration):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectConfiguration):
            return True

        return self.to_dict() != other.to_dict()
