# coding: utf-8

"""
    Teamscale REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.1.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class TokenElementChurnInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uniform_path': 'str',
        'change_type': 'str'
    }

    attribute_map = {
        'uniform_path': 'uniformPath',
        'change_type': 'changeType'
    }

    def __init__(self, uniform_path=None, change_type=None, local_vars_configuration=None):  # noqa: E501
        """TokenElementChurnInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._uniform_path = None
        self._change_type = None
        self.discriminator = None

        if uniform_path is not None:
            self.uniform_path = uniform_path
        if change_type is not None:
            self.change_type = change_type

    @property
    def uniform_path(self):
        """Gets the uniform_path of this TokenElementChurnInfo.  # noqa: E501


        :return: The uniform_path of this TokenElementChurnInfo.  # noqa: E501
        :rtype: str
        """
        return self._uniform_path

    @uniform_path.setter
    def uniform_path(self, uniform_path):
        """Sets the uniform_path of this TokenElementChurnInfo.


        :param uniform_path: The uniform_path of this TokenElementChurnInfo.  # noqa: E501
        :type: str
        """

        self._uniform_path = uniform_path

    @property
    def change_type(self):
        """Gets the change_type of this TokenElementChurnInfo.  # noqa: E501


        :return: The change_type of this TokenElementChurnInfo.  # noqa: E501
        :rtype: str
        """
        return self._change_type

    @change_type.setter
    def change_type(self, change_type):
        """Sets the change_type of this TokenElementChurnInfo.


        :param change_type: The change_type of this TokenElementChurnInfo.  # noqa: E501
        :type: str
        """
        allowed_values = ["ADD", "EDIT", "DELETE", "ORIGIN_CHANGE", "MOVE", "COPY", "EXTERNAL_ANALYSIS_UPLOAD"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and change_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `change_type` ({0}), must be one of {1}"  # noqa: E501
                .format(change_type, allowed_values)
            )

        self._change_type = change_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenElementChurnInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TokenElementChurnInfo):
            return True

        return self.to_dict() != other.to_dict()
